default_stages: [pre-commit, pre-push]
exclude: ^venv/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-docstring-first
      # - id: fix-encoding-pragma
      - id: trailing-whitespace
        exclude: CHANGELOG.md
      - id: end-of-file-fixer
        exclude: CHANGELOG.md
      - id: check-yaml
      # - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-symlinks
      - id: no-commit-to-branch
        args: [
            # "--branch",
            # "main",
            # "--branch",
            # "master",
            "--branch",
            "development",
            "--branch",
            "staging",
            "--branch",
            "production",
          ]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
