name: "django-boilerplate"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  server: &service
    container_name: server
    image: ducdat147/dj.base.project:latest
    command: /start-service
    labels:
      logging: "promtail"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - local-networks
      - devops-network
    depends_on:
      - database
      - redis
      - rabbitmq
    logging: *default-logging

  celery_worker:
    <<: *service
    container_name: celery_worker
    command: /start-celeryworker

  celery_beat:
    <<: *service
    container_name: celery_beat
    command: /start-celerybeat

  celery_flower:
    <<: *service
    container_name: celery_flower
    command: /start-celeryflower

  database:
    container_name: database
    image: postgres:16
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-networks
      - devops-network

  redis:
    container_name: redis
    image: redis:7.4-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-networks
      - devops-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./bash/devops/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-networks
      - devops-network

networks:
  local-networks:
    name: local-networks
  devops-network:
    name: devops-network
    external: true

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  redis_data:
    name: redis_data
  database_data:
    name: database_data
