name: "django-boilerplate-local"

services:
  server: &service
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.local
    command: /start-local
    environment:
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
      - /app/flower_db
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - 80:80
    depends_on:
      - database
      - redis
      - rabbitmq
    networks:
      - local-networks
      - devops-network

  celery_worker:
    <<: *service
    container_name: celery_worker
    command: /start-celeryworker
    ports: []

  celery_beat:
    <<: *service
    container_name: celery_beat
    command: /start-celerybeat
    ports: []

  celery_flower:
    <<: *service
    container_name: celery_flower
    command: /start-celeryflower
    ports:
      - 5555:5555

  database:
    container_name: database
    image: postgres:16
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-networks
      - devops-network

  redis:
    image: redis:7.4-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-networks
      - devops-network

  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./bash/devops/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-networks
      - devops-network

networks:
  local-networks:
  devops-network:
    name: devops-network
    external: true

volumes:
  server_data:
  rabbitmq_data:
  redis_data:
  database_data:
