[project]
name = "django-boilerplate"
version = "0.1.0"
description = "Add your description here"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=46.0.3",
    "django>=5.2.8",
    "django-allauth>=65.13.0",
    "django-autoslug>=1.9.9",
    "django-celery-beat>=2.8.1",
    "django-constance>=4.3.4",
    "django-cors-headers>=4.9.0",
    "django-crispy-forms>=2.5",
    "django-environ>=0.12.0",
    "django-filter>=25.2",
    "django-guardian>=3.2.0",
    "django-import-export>=4.3.14",
    "django-modeltranslation>=0.19.17",
    "django-money>=3.5.4",
    "django-phonenumber-field[phonenumbers]>=8.4.0",
    "django-rosetta>=0.10.2",
    "django-simple-history>=3.10.1",
    "django-unfold>=0.71.0",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.29.0",
    "flower>=2.0.1",
    "json-log-formatter>=1.1.1",
    "markdown>=3.10",
    "markupsafe>=3.0.3",
    "oauthlib>=3.3.1",
    "opentelemetry-exporter-otlp>=1.38.0",
    "opentelemetry-instrumentation-asgi>=0.59b0",
    "opentelemetry-instrumentation-celery>=0.59b0",
    "opentelemetry-instrumentation-django>=0.59b0",
    "opentelemetry-instrumentation-logging>=0.59b0",
    "opentelemetry-instrumentation-requests>=0.59b0",
    "opentelemetry-instrumentation-threading>=0.59b0",
    "opentelemetry-instrumentation-wsgi>=0.59b0",
    "pillow>=12.0.0",
    "psycopg>=3.2.12",
    "psycopg-binary>=3.2.12",
    "pygments>=2.19.2",
    "pyotp>=2.9.0",
    "pyupgrade>=3.21.1",
    "qrcode>=8.2",
    "redis>=7.0.1",
    "uwsgi>=2.0.31",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "flake8>=7.3.0",
    "pre-commit>=4.4.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "pytest-mock>=3.15.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.13.1",
]

[tool.ruff]
# Same as Black.
line-length = 120
indent-width = 4

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
