[project]
name = "django-boilerplate"
version = "0.1.0"
description = "Add your description here"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=49.0.0",
    "django>=6.0.7",
    "django-allauth>=65.18.0",
    "django-autoslug>=1.9.9",
    "django-celery-beat>=2.9.0",
    "django-constance>=4.3.5",
    "django-cors-headers>=4.9.0",
    "django-crispy-forms>=2.6",
    "django-environ>=0.14.0",
    "django-filter>=26.1",
    "django-guardian>=3.3.2",
    "django-hijack>=3.7.8",
    "django-import-export>=4.4.1",
    "django-json-widget>=2.1.1",
    "django-modeltranslation>=0.20.3",
    "django-money>=3.6.1",
    "django-phonenumber-field[phonenumberslite]>=8.4.0",
    "django-rosetta>=0.10.3",
    "django-simple-history>=3.12.0",
    "django-unfold>=0.100.0",
    "djangoql>=0.19.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "flower>=2.0.1",
    "json-log-formatter>=1.2.1",
    "markdown>=3.10.2",
    "markupsafe>=3.0.3",
    "oauthlib>=3.3.1",
    "opentelemetry-exporter-otlp>=1.43.0",
    "opentelemetry-instrumentation-asgi>=0.64b0",
    "opentelemetry-instrumentation-celery>=0.64b0",
    "opentelemetry-instrumentation-django>=0.64b0",
    "opentelemetry-instrumentation-logging>=0.64b0",
    "opentelemetry-instrumentation-requests>=0.64b0",
    "opentelemetry-instrumentation-threading>=0.64b0",
    "opentelemetry-instrumentation-wsgi>=0.64b0",
    "pillow>=12.3.0",
    "psycopg>=3.3.4",
    "psycopg-binary>=3.3.4",
    "pygments>=2.20.0",
    "pyotp>=2.10.0",
    "pyupgrade>=3.21.2",
    "qrcode>=8.2",
    "redis>=8.0.1",
    "uwsgi>=2.0.31",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "coverage>=7.15.0",
    "flake8>=7.3.0",
    "pre-commit>=4.6.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.12.0",
    "pytest-mock>=3.15.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.15.21",
]

[tool.ruff]
# Same as Black.
line-length = 120
indent-width = 4

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
