#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

db_ready() {
python << END
import sys
import time

import psycopg
from urllib.parse import urlparse

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        url = urlparse("${DATABASE_URL}")
        psycopg.connect(
            host=url.hostname,
            port=url.port,
            user=url.username,
            password=url.password,
            dbname=url.path[1:],
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END
}
until db_ready; do
  >&2 echo 'Waiting for Database to become available...'
  sleep 1
done
>&2 echo 'Database is available'

exec "$@"
