#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Collecting static files..."
python /app/manage.pyc collectstatic --noinput
echo "Running migrations..."
python /app/manage.pyc migrate
echo "Compiling message files..."
python /app/manage.pyc compilemessages
echo "Creating seed data..."
python /app/manage.pyc seed_data

uwsgi --ini /app/uwsgi.ini
