apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-webhook
    receivers:
      - uid: default-webhook
        type: webhook
        settings:
          url: ${GRAFANA_ALERT_WEBHOOK_URL}
          httpMethod: POST
