# Generated by Django 5.2.11 on 2026-02-13 02:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="to",
            field=models.CharField(db_index=True, max_length=255, verbose_name="To"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, db_index=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(fields=["to", "target", "type_otp"], name="otp_lookup_idx"),
        ),
    ]
