name: CI - Develop

on:
  pull_request:
    branches: [ "develop" ]
    types: [opened, synchronize, reopened]
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

permissions:
  contents: write
  pull-requests: write

env:
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/app_test"
  CACHE_URL: "redis://localhost:6379/0"
  DJANGO_SETTINGS_MODULE: "configurations.settings"
  CELERY_BROKER: "amqp://guest:guest@localhost:5672//"
  CELERY_BACKEND: "rpc://"
  CELERY_FLOWER_USER: "admin"
  CELERY_FLOWER_PASSWORD: "admin"
  PYTHONUNBUFFERED: "1"
  DEPLOYMENT_ENVIRONMENT: "test"
  PROJECT_NAME: "django"

jobs:
  test:
    name: Django Tests with uv
    runs-on: ubuntu-latest

    env:
      EMAIL_USE_TLS: "${{secrets.EMAIL_USE_TLS}}"
      EMAIL_USE_SSL: "${{secrets.EMAIL_USE_SSL}}"
      EMAIL_HOST: "${{secrets.EMAIL_HOST}}"
      EMAIL_PORT: "${{secrets.EMAIL_PORT}}"
      EMAIL_HOST_USER: "${{secrets.EMAIL_HOST_USER}}"
      EMAIL_HOST_PASSWORD: "${{secrets.EMAIL_HOST_PASSWORD}}"
      EMAIL_VERIFICATION_CODE_TIMEOUT: "${{secrets.EMAIL_VERIFICATION_CODE_TIMEOUT}}"

    services:
      postgres:
        image: postgres:16
        ports: [ "5432:5432" ]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        options: >-
          --health-cmd="pg_isready -U postgres -d app_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

      redis:
        image: redis:7
        ports: [ "6379:6379" ]
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

      rabbitmq:
        image: rabbitmq:3.11
        ports: [ "5672:5672", "15672:15672" ]
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Run migrations
        run: uv run python manage.py migrate --noinput

      - name: Run tests with coverage
        run: uv run coverage run manage.py test

      - name: Report coverage
        run: uv run coverage report -m

  automerge:
    name: Auto-merge
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Auto-merge
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
